### ISSUE TITLE
Max parallelism override on certain actions

### ISSUE THREAD

**Issue by LauJosefsen** [cego/gitte#135]
gitte.yml
```yml
actionOverride:
  down:
    maxParallelization: 1
  purge:
    maxParallelization: 1
```
