### ISSUE TITLE
.gitte-override.yml

### ISSUE THREAD

**Issue by firecow** [cego/gitte#47]
```yml
--- # .gitte.yml
projects:
  example-com:
    remote: git@gitlab.com:cego/example.com
    default_branch: master
    actions:
      up: ["docker-compose", "up"]
```

```yml
--- # .gitte-override.yml
projects:
  example-com:
    actions: {}
```

Config and Override files are deep extended enabling developers to opt-out or opt extra stuff in.
